### ISSUE TITLE
Please provide source for EX294 practice tasks

### ISSUE THREAD

**Issue by tsluyter** [nazunalika/linux-guide-and-hints#12]
Please be so kind as to provide the source for your EX294 practice tasks. 

They are identical to Tomas' work published on Lisenet in 2019.

-> https://www.lisenet.com/2019/ansible-sample-exam-for-ex407/

**Comment by nazunalika** [comment]
Closing as the page is being removed anyway in a future commit. Thanks.

**Comment by tsluyter** [comment]
Thanks for your swift response!
